---
title: Portfolio | Ivan-Asen - Web & Mobile Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vankata9907@gmail.com
description: 'Developer portfolio

'
url: https://ivanasen.github.io
markdown: kramdown
gems:
- jekyll-feed
- jekyll-minifier
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
